import{initializeApp}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import{getFirestore,collection,addDoc,doc,updateDoc,deleteDoc,onSnapshot,serverTimestamp,runTransaction}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
import{getStorage,ref,uploadBytes,uploadString,getDownloadURL,deleteObject}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-storage.js";
const firebaseConfig={apiKey:"AIzaSyDeKIZcW1Mvi4lYvaKRMOWdKk3ikFXwEAU",authDomain:"huah-198fc.firebaseapp.com",projectId:"huah-198fc",storageBucket:"huah-198fc.firebasestorage.app",messagingSenderId:"276648968284",appId:"1:276648968284:web:029616d17546aa7d662699",measurementId:"G-J8V7DB0DF7"};
const fb=initializeApp(firebaseConfig),db=getFirestore(fb),storage=getStorage(fb);const $=id=>document.getElementById(id);let role="user",tasks=[],started=false,editing=null,removeImage=false;
const ADMIN_USER="Admin",ADMIN_PASS="A2026",PARENT_PASS="F2026";
function selectRole(r){role=r;const admin=r==="admin";$("parentRoleBtn").classList.toggle("active",!admin);$("adminRoleBtn").classList.toggle("active",admin);$("usernameGroup").classList.toggle("hidden",!admin);$("usernameInput").value="";$("passwordInput").value="";$("loginBtn").textContent=admin?"Logga in som admin":"Logga in som förälder";$("loginError").classList.add("hidden");setTimeout(()=>$(admin?"usernameInput":"passwordInput").focus(),50)}
function enterApp(r){role=r;sessionStorage.setItem("fixday_access","ok");sessionStorage.setItem("fixday_role",r);$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");$("adminPanel").classList.toggle("hidden",r!=="admin");$("roleBadge").textContent=r==="admin"?"⚙️ Admin":"👤 Förälder";startApp();render()}
function login(){const u=$("usernameInput").value.trim(),p=$("passwordInput").value.trim();if(role==="admin"&&u===ADMIN_USER&&p===ADMIN_PASS)enterApp("admin");else if(role==="user"&&p===PARENT_PASS)enterApp("user");else{$("loginError").classList.remove("hidden");$("passwordInput").value="";$("passwordInput").focus()}}
$("parentRoleBtn").onclick=()=>selectRole("user");$("adminRoleBtn").onclick=()=>selectRole("admin");$("loginBtn").onclick=login;$("usernameInput").onkeydown=e=>{if(e.key==="Enter")$("passwordInput").focus()};$("passwordInput").onkeydown=e=>{if(e.key==="Enter")login()};$("logoutBtn").onclick=()=>{sessionStorage.clear();location.reload()};$("formToggle").onclick=()=>{const c=$("adminPanel").classList.toggle("collapsed");$("formToggle").setAttribute("aria-expanded",String(!c))};
function startApp(){if(started)return;started=true;onSnapshot(collection(db,"tasks"),s=>{tasks=s.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));render()},e=>{$("taskList").innerHTML='<div class="empty">Det gick inte att hämta uppgifterna.</div>';console.error(e)})}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;")}
function imageHtml(t){if(!t.imageUrl)return'<div class="no-img">📷<span>Ingen bild</span></div>';return`<div class="card-image"><img class="card-img" src="${esc(t.imageUrl)}" alt="Uppgiftsbild" loading="lazy" data-img><div class="image-error">📷<span>Bilden kunde inte laddas</span></div></div>`}
function isTaskCompleted(t){const people=Array.isArray(t.people)?t.people:[];return people.length>0&&people.every(p=>p.done===true)}
function createTaskCard(t){const people=Array.isArray(t.people)?t.people:[],max=Number(t.max)||1,full=people.length>=max,pct=Math.min(100,Math.round(people.length/max*100));const persons=people.length?people.map((p,i)=>`<div class="person"><span>${p.done?"✅":"⏳"} ${esc(p.name)}</span><span class="badge ${p.done?"done":"waiting"}">${p.done?"Slutförd":"Pågår"}</span></div>${role==="admin"?`<div class="actions">${!p.done?`<button class="success" data-a="done" data-id="${t.id}" data-i="${i}">Markera som klar</button>`:""}<button class="danger" data-a="remove" data-id="${t.id}" data-i="${i}">Ta bort person</button></div>`:""}`).join(""):'<p class="muted" style="margin-top:10px">Inga deltagare ännu</p>';return`<article class="card ${full?"full":""}">${imageHtml(t)}<div class="content"><h3 class="task-title">${esc(t.name)}</h3><p class="description">${esc(t.description||"")}</p><div class="progress-row"><span>Deltagare</span><strong>${people.length}/${max}</strong></div><div class="progress"><div class="progress-fill" style="width:${pct}%"></div></div>${persons}<div class="actions"><button class="success" data-a="join" data-id="${t.id}" ${full?"disabled":""}>${full?"Uppgiften är full":"Anmäl mig"}</button>${role==="user"?`<button class="secondary" data-a="complete-self" data-id="${t.id}">Markera min uppgift som klar</button>`:""}${role==="admin"?`<button class="secondary" data-a="edit" data-id="${t.id}">Redigera</button><button class="danger" data-a="delete" data-id="${t.id}">Radera</button>`:""}</div></div></article>`}
function render(){if(!$("taskList"))return;let total=0;tasks.forEach(t=>total+=(t.people||[]).length);$("taskCount").textContent=tasks.length;$("participantCount").textContent=total;if(!tasks.length){$("taskList").innerHTML='<div class="empty">Inga uppgifter ännu.</div>';return}const activeTasks=tasks.filter(t=>!isTaskCompleted(t)),completedTasks=tasks.filter(isTaskCompleted);const activeHtml=activeTasks.map(createTaskCard).join("");const completedHtml=completedTasks.map(createTaskCard).join("");$("taskList").innerHTML=`${activeHtml||'<div class="empty">Inga aktiva uppgifter.</div>'}${completedTasks.length?`<div class="task-section"><button id="completedToggle" class="task-toggle" type="button" aria-expanded="false"><span>✅ Slutförda uppgifter (${completedTasks.length})</span><span class="toggle-icon">⌄</span></button><div id="completedWrapper" class="completed-wrapper">${completedHtml}</div></div>`:""}`;const toggle=$("completedToggle");if(toggle)toggle.onclick=()=>{const open=$("completedWrapper").classList.toggle("open");toggle.setAttribute("aria-expanded",String(open))}}
$("taskList").addEventListener("error",e=>{if(e.target.matches("img[data-img]")){e.target.style.display="none";e.target.nextElementSibling.style.display="flex"}},true);
$("taskList").onclick=async e=>{const b=e.target.closest("button");if(!b)return;const a=b.dataset.a,id=b.dataset.id,i=Number(b.dataset.i);if(a==="join")await join(id);else if(a==="complete-self")await completeSelf(id);else if(role!=="admin")return;else if(a==="edit")openEdit(id);else if(a==="delete")await del(id);else if(a==="done")await personUpdate(id,i,"done");else if(a==="remove")await personUpdate(id,i,"remove")};
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=e=>{const im=new Image();im.onload=()=>{let w=im.width,h=im.height;if(w>1000){h=Math.round(h*1000/w);w=1000}const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(im,0,0,w,h);resolve(c.toDataURL("image/jpeg",.75))};im.onerror=reject;im.src=e.target.result};r.onerror=reject;r.readAsDataURL(file)})}
async function upload(file){const path=`task-images/task_${Date.now()}.${file.name.split(".").pop()||"jpg"}`,r=ref(storage,path);try{await uploadString(r,await compress(file),"data_url")}catch{await uploadBytes(r,file)}return{imageUrl:await getDownloadURL(r),imagePath:path}}
$("createTaskBtn").onclick=async()=>{if(role!=="admin")return;const name=$("taskName").value.trim(),description=$("taskDescription").value.trim(),max=parseInt($("taskMax").value)||1,file=$("taskImage").files[0];if(!name)return alert("Ange ett namn på uppgiften.");const b=$("createTaskBtn");b.disabled=true;try{let imageUrl="",imagePath="";if(file)({imageUrl,imagePath}=await upload(file));await addDoc(collection(db,"tasks"),{name,description,max,imageUrl,imagePath,people:[],createdAt:serverTimestamp()});$("taskName").value="";$("taskDescription").value="";$("taskMax").value="1";$("taskImage").value="";$("createStatus").textContent="Uppgiften har skapats ✅";setTimeout(()=>{$("createStatus").textContent="";$("adminPanel").classList.add("collapsed");$("formToggle").setAttribute("aria-expanded","false")},1500)}catch(e){console.error(e);$("createStatus").textContent="Ett fel inträffade."}finally{b.disabled=false}};
async function join(id){const n=prompt("Ange ditt namn:");if(!n?.trim())return;try{await runTransaction(db,async tx=>{const r=doc(db,"tasks",id),s=await tx.get(r);if(!s.exists())throw Error("Uppgiften finns inte.");const d=s.data(),p=Array.isArray(d.people)?[...d.people]:[];if(p.some(x=>x.name.toLowerCase()===n.trim().toLowerCase()))throw Error("Du är redan anmäld.");if(p.length>=(d.max||1))throw Error("Uppgiften är full.");p.push({name:n.trim(),done:false});tx.update(r,{people:p})})}catch(e){alert(e.message)}}
async function completeSelf(id){const name=prompt("Ange samma namn som du använde vid anmälan:");if(!name?.trim())return;try{await runTransaction(db,async tx=>{const taskRef=doc(db,"tasks",id),snapshot=await tx.get(taskRef);if(!snapshot.exists())throw Error("Uppgiften finns inte längre.");const data=snapshot.data(),people=Array.isArray(data.people)?data.people.map(person=>({...person})):[];const index=people.findIndex(person=>String(person.name||"").toLocaleLowerCase("sv-SE")===name.trim().toLocaleLowerCase("sv-SE"));if(index<0)throw Error("Namnet finns inte bland de anmälda till uppgiften.");if(people[index].done===true)throw Error("Uppgiften är redan markerad som slutförd.");people[index].done=true;tx.update(taskRef,{people})});alert("Uppgiften har markerats som slutförd ✅")}catch(error){alert(error.message||"Det gick inte att uppdatera uppgiften.")}}
function openEdit(id){editing=tasks.find(t=>t.id===id);if(!editing)return;$("editName").value=editing.name||"";$("editDescription").value=editing.description||"";$("editMax").value=editing.max||1;$("editImage").value="";removeImage=false;if(editing.imageUrl){$("editPreview").src=editing.imageUrl;$("currentImageBox").classList.remove("hidden")}else $("currentImageBox").classList.add("hidden");$("editModal").classList.remove("hidden")}
$("cancelEditBtn").onclick=()=>$("editModal").classList.add("hidden");$("removeImageBtn").onclick=()=>{removeImage=true;$("currentImageBox").classList.add("hidden")};$("saveEditBtn").onclick=async()=>{if(!editing||role!=="admin")return;const data={name:$("editName").value.trim(),description:$("editDescription").value.trim(),max:parseInt($("editMax").value)||1},file=$("editImage").files[0];if(!data.name)return alert("Ange ett namn.");try{let newPath="";if(file){const u=await upload(file);Object.assign(data,u);newPath=u.imagePath}else if(removeImage){data.imageUrl="";data.imagePath=""}await updateDoc(doc(db,"tasks",editing.id),data);if((file||removeImage)&&editing.imagePath&&editing.imagePath!==newPath)deleteObject(ref(storage,editing.imagePath)).catch(console.warn);$("editModal").classList.add("hidden")}catch(e){alert("Det gick inte att spara.")}};
async function del(id){const t=tasks.find(x=>x.id===id);if(!t||!confirm(`Radera ${t.name}?`))return;await deleteDoc(doc(db,"tasks",id));if(t.imagePath)deleteObject(ref(storage,t.imagePath)).catch(console.warn)}
async function personUpdate(id,i,mode){await runTransaction(db,async tx=>{const r=doc(db,"tasks",id),s=await tx.get(r),p=s.data().people.map(x=>({...x}));if(mode==="done")p[i].done=true;else if(confirm(`Ta bort ${p[i].name}?`))p.splice(i,1);else return;tx.update(r,{people:p})})}
const savedRole=sessionStorage.getItem("fixday_role");if(sessionStorage.getItem("fixday_access")==="ok"&&(savedRole==="admin"||savedRole==="user"))enterApp(savedRole);else selectRole("user");
